# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_lenght',
            new_name='product_length',
        ),
    ]
